# Generated by Django 3.0.4 on 2020-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
